version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - 27017
    ports:
      - '27017:27017'